---
- name: "Wait until server is accessible"
  uri:
    url: "https://{{ keycloak_server }}/"
    status_code: 200
    validate_certs: no
  register: result
  ignore_errors: yes
  until: result.status == 200
  retries: 3
  delay: 10  

- name: Add clientrole for user
  command: "make kcadmn cmd='add-roles -r {{ keycloak_realm }} --uusername {{ keycloak_username }} --cclientid {{ keycloak_client_name }} --rolename {{ keycloak_role }}'"
  args:
    chdir: "{{ user_path }}/{{ keycloak_deploy_name }}"
  register: result_cr
  ignore_errors: yes

#- debug: var=result_make.stdout_lines